### ISSUE TITLE
Simulation: invalid thread access after Map Node edges are registered

### ISSUE THREAD

**Issue by MicheleMUC** [BauhausLuftfahrt/PAXelerate#106]
Using the _TestCabin_v0.6.xmi_ causes the follwoing error:

``` java
!ENTRY net.bhl.cdt.paxelerate.model 1 0 2016-03-30 17:59:20.819
!MESSAGE Map Node edges registered
Exception in thread "8 (2B)" org.eclipse.swt.SWTException: Invalid thread access
    at org.eclipse.swt.SWT.error(SWT.java:4491)
    at org.eclipse.swt.SWT.error(SWT.java:4406)
    at org.eclipse.swt.SWT.error(SWT.java:4377)
    at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
    at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:373)
    at org.eclipse.swt.widgets.Table.getItems(Table.java:2669)
    at org.eclipse.jface.viewers.TableViewer.doGetItems(TableViewer.java:233)
    at org.eclipse.jface.viewers.AbstractTableViewer.doFindItem(AbstractTableViewer.java:328)
    at org.eclipse.jface.viewers.TableViewer.doFindItem(TableViewer.java:458)
    at org.eclipse.jface.viewers.StructuredViewer.findItems(StructuredViewer.java:811)
    at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2093)
    at org.eclipse.jface.viewers.ColumnViewer.update(ColumnViewer.java:541)
    at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2041)
    at org.eclipse.jface.viewers.StructuredViewer.handleLabelProviderChanged(StructuredViewer.java:1208)
    at org.eclipse.jface.viewers.ContentViewer$1.labelProviderChanged(ContentViewer.java:99)
    at org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider.notifyChanged(AdapterFactoryLabelProvider.java:917)
    at org.eclipse.emf.edit.provider.ChangeNotifier.fireNotifyChanged(ChangeNotifier.java:45)
    at org.eclipse.emf.edit.provider.ComposedAdapterFactory.fireNotifyChanged(ComposedAdapterFactory.java:469)
    at org.eclipse.emf.edit.provider.ReflectiveItemProviderAdapterFactory.fireNotifyChanged(ReflectiveItemProviderAdapterFactory.java:148)
    at org.eclipse.emf.edit.provider.ItemProviderAdapter.fireNotifyChanged(ItemProviderAdapter.java:245)
    at org.eclipse.emf.edit.provider.ReflectiveItemProvider.notifyChanged(ReflectiveItemProvider.java:737)
    at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
    at net.bhl.cdt.paxelerate.model.impl.PassengerImpl.setPositionX(PassengerImpl.java:728)
    at net.bhl.cdt.paxelerate.model.agent.Agent.followPath(Agent.java:697)
    at net.bhl.cdt.paxelerate.model.agent.Agent.run(Agent.java:942)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by marcengelmann** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/16258698/14171184/eea2284a-f731-11e5-9eb4-c52f1f0c5cde.PNG)

works for me

**Comment by MicheleMUC** [comment]
@marcengelmann after deleting all stored temporary data, I can't reproduce it either.
