### ISSUE TITLE
Concurrent Modification Exception in GeneratePAX

### ISSUE THREAD

**Issue by marcengelmann** [BauhausLuftfahrt/PAXelerate#115]
``` java
Root exception:
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at org.eclipse.emf.emfstore.internal.client.model.impl.ProjectSpaceBase.addOperations(ProjectSpaceBase.java:218)
    at org.eclipse.emf.emfstore.internal.client.model.impl.OperationManager.operationsRecorded(OperationManager.java:156)
    at org.eclipse.emf.emfstore.internal.client.model.impl.OperationRecorder.operationsRecorded(OperationRecorder.java:306)
    at org.eclipse.emf.emfstore.internal.client.model.impl.OperationRecorder.commandCompleted(OperationRecorder.java:523)
    at org.eclipse.emf.emfstore.internal.client.model.impl.OperationRecorder.commandCompleted(OperationRecorder.java:471)
    at org.eclipse.emf.emfstore.internal.client.model.impl.OperationManager.commandCompleted(OperationManager.java:205)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.emf.emfstore.internal.common.observer.ObserverBus$ProxyHandler.notifiyObservers(ObserverBus.java:309)
    at org.eclipse.emf.emfstore.internal.common.observer.ObserverBus$ProxyHandler.invoke(ObserverBus.java:277)
    at com.sun.proxy.$Proxy21.commandCompleted(Unknown Source)
    at org.eclipse.emf.emfstore.internal.client.model.changeTracking.commands.EMFStoreCommandNotifier.notifiyListenersAboutCommandCompleted(EMFStoreCommandNotifier.java:72)
    at org.eclipse.emf.emfstore.internal.client.model.changeTracking.commands.EMFStoreBasicCommandStack.execute(EMFStoreBasicCommandStack.java:79)
    at org.eclipse.emf.emfstore.internal.client.model.util.AbstractEMFStoreCommand.aRun(AbstractEMFStoreCommand.java:108)
    at org.eclipse.emf.emfstore.internal.client.model.util.EMFStoreCommand.run(EMFStoreCommand.java:60)
    at org.eclipse.emf.emfstore.client.util.RunESCommand.run(RunESCommand.java:145)
    at org.eclipse.emf.ecp.emfstore.core.internal.EMFStoreProvider.fillChildren(EMFStoreProvider.java:164)
    at org.eclipse.emf.ecp.internal.core.ECPProviderRegistryImpl$ProviderDescriptor.fillChildren(ECPProviderRegistryImpl.java:222)
    at org.eclipse.emf.ecp.internal.ui.model.ECPContentProvider.fillChildren(ECPContentProvider.java:50)
    at org.eclipse.emf.ecp.internal.ui.model.ModelContentProvider.fillChildren(ModelContentProvider.java:68)
    at org.eclipse.emf.ecp.internal.ui.model.TreeContentProvider.fillChildrenDetectError(TreeContentProvider.java:198)
    at org.eclipse.emf.ecp.internal.ui.model.TreeContentProvider.getChildrenList(TreeContentProvider.java:190)
    at org.eclipse.emf.ecp.internal.ui.model.TreeContentProvider.getChildren(TreeContentProvider.java:81)
    at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1372)
    at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:353)
    at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:906)
    at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:617)
    at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2647)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1916)
    at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1923)
    at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1891)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1841)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1834)
    at org.eclipse.jface.viewers.StructuredViewer$7.run(StructuredViewer.java:1526)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1462)
    at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:366)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1423)
    at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1523)
    at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:522)
    at org.eclipse.emf.ecp.internal.ui.model.TreeContentProvider.refresh(TreeContentProvider.java:211)
    at org.eclipse.emf.ecp.internal.ui.model.TreeContentProvider$1.run(TreeContentProvider.java:160)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at net.bhl.cdt.client.Application.start(Application.java:26)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

**Comment by RRothfeld** [comment]
Der Fehler kommt von der Verwendung mehrerer Threads und hat zur Zeit keine Auswirkungen auf die Ausführung des Programmes.

Wie es zu beheben ist weiß ich nicht, nachdem ich versucht hatte mögliche Funktionen zu synchronisiern...

**Comment by MicheleMUC** [comment]
already fixed in release 0.7-alpha
