### ISSUE TITLE
InterruptedException: Passenger did not react

### ISSUE THREAD

**Issue by MicheleMUC** [BauhausLuftfahrt/PAXelerate#150]
Running batch simulation:

``` java
sleep check
35(29A)has caused interuption!

!ENTRY net.bhl.cdt.paxelerate.ui 1 0 2016-07-15 05:47:02.222
!MESSAGE SIMULATION TERMINATED! Passenger 35(29A) did not react.

!ENTRY net.bhl.cdt.paxelerate.util 1 0 2016-07-15 05:47:02.223
!MESSAGE Start data export...

!ENTRY net.bhl.cdt.paxelerate.util 1 0 2016-07-15 05:47:02.247
!MESSAGE ...data export complete.
Simulation Handler resetted!

!ENTRY net.bhl.cdt.paxelerate.ui 1 0 2016-07-15 05:47:02.248
!MESSAGE Simulation run failed!

!ENTRY net.bhl.cdt.paxelerate.ui 1 0 2016-07-15 05:47:02.249
!MESSAGE Loading cabin from file...

!ENTRY org.eclipse.emf.ecp.emfstore.core 1 0 2016-07-15 05:47:02.264
!MESSAGE EMFStoreProvider received REMOVE for ECPProjectImpl reference
InterruptedException @ thread 38(29B)
InterruptedException @ thread 35(29A)
InterruptedException @ thread 113(29C)

!ENTRY org.eclipse.emf.ecp.emfstore.core 1 0 2016-07-15 05:47:02.317
!MESSAGE EMFStoreProvider received INIT for ECPProjectImpl reference

!ENTRY org.eclipse.emf.ecp.emfstore.core 1 0 2016-07-15 05:47:02.317
!MESSAGE EMFStoreProvider received CREATE for ECPProjectImpl reference
java.lang.InterruptedException: sleep interrupted
    at java.lang.Thread.sleep(Native Method)
    at net.bhl.cdt.paxelerate.model.agent.PassiveMood.reactToCollision(PassiveMood.java:41)
    at net.bhl.cdt.paxelerate.model.agent.Situation.handle(Situation.java:39)
    at net.bhl.cdt.paxelerate.model.agent.Agent.followPath(Agent.java:1323)
    at net.bhl.cdt.paxelerate.model.agent.Agent.run(Agent.java:1591)
    at java.lang.Thread.run(Unknown Source)
java.lang.InterruptedException: sleep interrupted
    at java.lang.Thread.sleep(Native Method)
    at net.bhl.cdt.paxelerate.model.agent.PassiveMood.reactToCollision(PassiveMood.java:41)
    at net.bhl.cdt.paxelerate.model.agent.Situation.handle(Situation.java:39)
    at net.bhl.cdt.paxelerate.model.agent.Agent.followPath(Agent.java:1323)
    at net.bhl.cdt.paxelerate.model.agent.Agent.run(Agent.java:1591)
    at java.lang.Thread.run(Unknown Source)
java.lang.InterruptedException: sleep interrupted
    at java.lang.Thread.sleep(Native Method)
    at net.bhl.cdt.paxelerate.model.agent.PassiveMood.reactToCollision(PassiveMood.java:41)
    at net.bhl.cdt.paxelerate.model.agent.Situation.handle(Situation.java:39)
    at net.bhl.cdt.paxelerate.model.agent.Agent.followPath(Agent.java:1323)
    at net.bhl.cdt.paxelerate.model.agent.Agent.run(Agent.java:1591)
    at java.lang.Thread.run(Unknown Source)
Exception in thread "35(29A)" Exception in thread "38(29B)" java.lang.NullPointerException
    at net.bhl.cdt.paxelerate.model.agent.Agent.followPath(Agent.java:1286)
    at net.bhl.cdt.paxelerate.model.agent.Agent.run(Agent.java:1591)
    at java.lang.Thread.run(Unknown Source)
Exception in thread "113(29C)" java.lang.NullPointerException
    at net.bhl.cdt.paxelerate.model.agent.Agent.followPath(Agent.java:1286)
    at net.bhl.cdt.paxelerate.model.agent.Agent.run(Agent.java:1591)
    at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
    at net.bhl.cdt.paxelerate.model.agent.Agent.followPath(Agent.java:1286)
    at net.bhl.cdt.paxelerate.model.agent.Agent.run(Agent.java:1591)
    at java.lang.Thread.run(Unknown Source)

!ENTRY net.bhl.cdt.paxelerate.ui 1 0 2016-07-15 05:47:02.357
!MESSAGE ...cabin loaded!

!ENTRY net.bhl.cdt.paxelerate.ui 1 0 2016-07-15 05:47:02.358
!MESSAGE ECP model import completed
```

**Comment by DianaAbouKharoub** [comment]
Hello Michael,

I have been getting this error and the same output in my console.
What could be causing this problem, and how can it be solved?

Regards,
Diana.
